# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.serviceprovider'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='marketplace.servicelisting'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_active', '-rating'], name='marketplace_is_acti_a04133_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['category', 'is_active'], name='marketplace_categor_fec6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['provider', 'is_active'], name='marketplace_provide_40eabb_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['listing', 'status'], name='marketplace_listing_1c8f37_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['sender', 'status'], name='marketplace_sender__f1852f_idx'),
        ),
    ]
