# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('brainstorm', 'Brainstorm Ideas'), ('content', 'Content'), ('plan', 'Strategic Plan'), ('analysis', 'Analysis'), ('code', 'Code'), ('design', 'Design'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional output metadata')),
                ('is_saved', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Output',
                'verbose_name_plural': 'AI Outputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('cothink', 'CoThink - Brainstorming'), ('cowrite', 'CoWrite - Content Creation'), ('coplan', 'CoPlan - Strategic Planning'), ('coanalyze', 'CoAnalyze - Data Analysis'), ('cocode', 'CoCode - Code Assistant'), ('codesign', 'CoDesign - Design Ideas')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Session context and parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Session',
                'verbose_name_plural': 'AI Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
