# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_cofounder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aioutput',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='ai_cofounder.aisession'),
        ),
        migrations.AddField(
            model_name='aioutput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_outputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_cofounder.aisession'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['user', '-created_at'], name='ai_cofounde_user_id_55a850_idx'),
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['tool', '-created_at'], name='ai_cofounde_tool_6dc22a_idx'),
        ),
        migrations.AddIndex(
            model_name='aioutput',
            index=models.Index(fields=['user', '-created_at'], name='ai_cofounde_user_id_de020f_idx'),
        ),
        migrations.AddIndex(
            model_name='aioutput',
            index=models.Index(fields=['output_type', '-created_at'], name='ai_cofounde_output__48d0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_cofounde_session_4a1a1d_idx'),
        ),
    ]
