# Generated by Django 4.2.16 on 2025-11-24 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_name', models.CharField(help_text='Name for external shareholders', max_length=200)),
                ('shareholder_type', models.CharField(choices=[('founder', 'Founder'), ('cofounder', 'Co-Founder'), ('employee', 'Employee'), ('advisor', 'Advisor'), ('investor', 'Investor'), ('other', 'Other')], max_length=20)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('share_class', models.CharField(default='Common', help_text='e.g., Common, Preferred, Series A, etc.', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cap Table Entry',
                'verbose_name_plural': 'Cap Table',
                'ordering': ['-ownership_percentage'],
            },
        ),
        migrations.CreateModel(
            name='EquityCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_contribution', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_commitment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('capital_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('skills_expertise', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_taken', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calculated_equity', models.DecimalField(decimal_places=2, default=0, help_text='Calculated equity percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('agreed_equity', models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed equity percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('role', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equity Calculation',
                'verbose_name_plural': 'Equity Calculations',
                'ordering': ['-calculated_equity'],
            },
        ),
        migrations.CreateModel(
            name='VestingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('time_based', 'Time-Based'), ('milestone_based', 'Milestone-Based'), ('hybrid', 'Hybrid')], default='time_based', max_length=20)),
                ('total_equity', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cliff_months', models.IntegerField(default=12, help_text='Cliff period in months', validators=[django.core.validators.MinValueValidator(0)])),
                ('vesting_period_months', models.IntegerField(default=48, help_text='Total vesting period in months', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('cliff_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('milestones', models.JSONField(blank=True, default=list, help_text='List of milestone objects for milestone-based vesting')),
                ('vested_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equity_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vesting_schedules', to='equity.equitycalculation')),
            ],
            options={
                'verbose_name': 'Vesting Schedule',
                'verbose_name_plural': 'Vesting Schedules',
                'ordering': ['-created_at'],
            },
        ),
    ]
