# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('equity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitycalculation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_calculations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equitycalculation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_calculations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='captable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_table_entries', to='projects.project'),
        ),
        migrations.AddField(
            model_name='captable',
            name='shareholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cap_table_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='equitycalculation',
            unique_together={('project', 'member')},
        ),
        migrations.AddIndex(
            model_name='captable',
            index=models.Index(fields=['project', '-ownership_percentage'], name='equity_capt_project_ef07b1_idx'),
        ),
    ]
