# Generated by Django 4.2.16 on 2025-11-24 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('workshop', 'Workshop'), ('webinar', 'Webinar'), ('networking', 'Networking'), ('conference', 'Conference'), ('meetup', 'Meetup'), ('pitch_event', 'Pitch Event'), ('hackathon', 'Hackathon'), ('other', 'Other')], max_length=20)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('marketing', 'Marketing'), ('design', 'Design'), ('finance', 'Finance'), ('startup', 'Startup'), ('entrepreneurship', 'Entrepreneurship'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(blank=True, help_text="Physical location or 'Online'", max_length=255)),
                ('location_details', models.TextField(blank=True, help_text='Additional location details or meeting link')),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True, help_text='Online meeting link')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='0 for free events', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees (null for unlimited)', null=True)),
                ('registered_count', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('speakers', models.JSONField(blank=True, default=list, help_text='List of speaker objects')),
                ('agenda', models.JSONField(blank=True, default=list, help_text='Event agenda/schedule')),
                ('banner_image', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='registered', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="User's notes or questions")),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
            },
        ),
    ]
