# Generated by Django 4.2.16 on 2025-11-24 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitchBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cofounder', 'Co-Founder'), ('technical_lead', 'Technical Lead'), ('cto', 'CTO'), ('cmo', 'CMO'), ('coo', 'COO'), ('advisor', 'Advisor'), ('developer', 'Developer'), ('designer', 'Designer'), ('marketer', 'Marketer'), ('sales', 'Sales Lead'), ('investor', 'Investor'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('equity_offer', models.DecimalField(blank=True, decimal_places=2, help_text='Equity percentage offered (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_commitment', models.CharField(blank=True, help_text='e.g., Full-time, Part-time, 10 hours/week', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('compatibility_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PitchBack',
                'verbose_name_plural': 'PitchBacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
