# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitches', '0001_initial'),
        ('pitchbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchback',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitchbacks', to='pitches.pitch'),
        ),
    ]
