# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitchbacks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchback',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pitchbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pitchback',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pitchbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pitchback',
            index=models.Index(fields=['pitch', '-created_at'], name='pitchbacks__pitch_i_44e5da_idx'),
        ),
        migrations.AddIndex(
            model_name='pitchback',
            index=models.Index(fields=['sender', '-created_at'], name='pitchbacks__sender__756f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='pitchback',
            index=models.Index(fields=['receiver', '-created_at'], name='pitchbacks__receive_cd8249_idx'),
        ),
        migrations.AddIndex(
            model_name='pitchback',
            index=models.Index(fields=['status', '-created_at'], name='pitchbacks__status_dea6a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pitchback',
            unique_together={('pitch', 'sender')},
        ),
    ]
