# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_name', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('solution_description', models.TextField()),
                ('target_audience', models.TextField()),
                ('validation_methods', models.JSONField(blank=True, default=list, help_text='Methods used for validation (surveys, interviews, etc.)')),
                ('survey_results', models.JSONField(blank=True, default=dict)),
                ('interview_notes', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('threats', models.JSONField(blank=True, default=list)),
                ('validation_score', models.IntegerField(default=0, help_text='Validation score out of 100')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Idea Validation',
                'verbose_name_plural': 'Idea Validations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=200)),
                ('market_size', models.CharField(blank=True, max_length=200)),
                ('growth_rate', models.CharField(blank=True, max_length=100)),
                ('target_segments', models.JSONField(blank=True, default=list)),
                ('customer_personas', models.JSONField(blank=True, default=list)),
                ('competitors', models.JSONField(blank=True, default=list, help_text='List of competitor objects')),
                ('competitive_advantages', models.JSONField(blank=True, default=list)),
                ('trends', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('barriers', models.JSONField(blank=True, default=list)),
                ('pricing_data', models.JSONField(blank=True, default=dict, help_text='Pricing strategies and competitor pricing')),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Research',
                'verbose_name_plural': 'Market Research',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MVPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goals', models.JSONField(blank=True, default=list)),
                ('core_features', models.JSONField(blank=True, default=list, help_text='Must-have features for MVP')),
                ('nice_to_have_features', models.JSONField(blank=True, default=list, help_text='Optional features for future iterations')),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('infrastructure_needs', models.JSONField(blank=True, default=list)),
                ('team_requirements', models.JSONField(blank=True, default=list)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_timeline_weeks', models.IntegerField(blank=True, null=True)),
                ('success_metrics', models.JSONField(blank=True, default=list, help_text='KPIs to measure MVP success')),
                ('launch_strategy', models.TextField(blank=True)),
                ('target_users_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_development', 'In Development'), ('testing', 'Testing'), ('launched', 'Launched')], default='planning', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_launch_date', models.DateField(blank=True, null=True)),
                ('actual_launch_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MVP Plan',
                'verbose_name_plural': 'MVP Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('subscription', 'Subscription'), ('freemium', 'Freemium'), ('one_time', 'One-time Purchase'), ('advertising', 'Advertising'), ('marketplace', 'Marketplace'), ('saas', 'SaaS'), ('licensing', 'Licensing'), ('hybrid', 'Hybrid'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('pricing_tiers', models.JSONField(blank=True, default=list, help_text='List of pricing tier objects')),
                ('revenue_streams', models.JSONField(blank=True, default=list, help_text='Different sources of revenue')),
                ('projections', models.JSONField(blank=True, default=dict, help_text='Revenue projections by time period')),
                ('cost_structure', models.JSONField(blank=True, default=dict, help_text='Fixed and variable costs')),
                ('key_metrics', models.JSONField(blank=True, default=list, help_text='Important metrics to track (CAC, LTV, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revenue Model',
                'verbose_name_plural': 'Revenue Models',
                'ordering': ['-created_at'],
            },
        ),
    ]
