# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('sprint_tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuemodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenuemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_models', to='projects.project'),
        ),
        migrations.AddField(
            model_name='mvpplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mvpplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_plans', to='projects.project'),
        ),
        migrations.AddField(
            model_name='marketresearch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_research', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketresearch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_research', to='projects.project'),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_validations', to='projects.project'),
        ),
    ]
