# Generated by Django 4.2.16 on 2025-11-30 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitches', '0005_pitch_additional_info_pitch_equity_offer_and_more'),
        ('sprint_tools', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_narrative', models.TextField(blank=True, default='')),
                ('problem_solution', models.JSONField(blank=True, default=dict, help_text='Problem, Solution, and Target fields')),
                ('value_proposition_canvas', models.JSONField(blank=True, default=dict, help_text='Gains, Pains, Gain Creators, Pain Relievers')),
                ('assumptions_log', models.JSONField(blank=True, default=list, help_text='List of assumptions with validation status')),
                ('market_analysis', models.JSONField(blank=True, default=dict, help_text='TAM, SAM, SOM values')),
                ('icp_profile', models.JSONField(blank=True, default=dict, help_text='Ideal Customer Profile data')),
                ('competitors', models.JSONField(blank=True, default=list, help_text='List of competitors with strengths/weaknesses')),
                ('user_surveys', models.JSONField(blank=True, default=list, help_text='List of user surveys conducted')),
                ('validation_score', models.JSONField(blank=True, default=dict, help_text='Problem, Solution, Market validation scores')),
                ('key_insights', models.JSONField(blank=True, default=list, help_text='Key insights gathered during validation')),
                ('pain_points', models.JSONField(blank=True, default=list, help_text='Mapped customer pain points')),
                ('feature_priorities', models.JSONField(blank=True, default=list, help_text='Features with impact/effort scores')),
                ('user_stories', models.JSONField(blank=True, default=list, help_text='User story mapping data')),
                ('mvp_feature_set', models.JSONField(blank=True, default=list, help_text='Core MVP features')),
                ('prd', models.JSONField(blank=True, default=dict, help_text='Product Requirements Document sections')),
                ('technical_architecture', models.JSONField(blank=True, default=dict, help_text='Frontend, Backend, Infrastructure, Third Party')),
                ('user_flows', models.JSONField(blank=True, default=dict, help_text='Primary and Secondary user flows')),
                ('wireframes', models.JSONField(blank=True, default=list, help_text='List of wireframe objects')),
                ('prototype', models.JSONField(blank=True, default=dict, help_text='Prototype URL and notes')),
                ('sprint_plans', models.JSONField(blank=True, default=list, help_text='List of sprint plans')),
                ('task_board', models.JSONField(blank=True, default=dict, help_text='Kanban board with todo, inProgress, review, done')),
                ('dev_milestones', models.JSONField(blank=True, default=list, help_text='Development milestones')),
                ('test_plan', models.JSONField(blank=True, default=dict, help_text='Test scenarios and plans')),
                ('beta_users', models.JSONField(blank=True, default=list, help_text='List of beta testers')),
                ('bugs', models.JSONField(blank=True, default=list, help_text='Bug tracker list')),
                ('usability_results', models.JSONField(blank=True, default=list, help_text='Usability testing results')),
                ('performance_metrics', models.JSONField(blank=True, default=dict, help_text='Load time, API time, error rate')),
                ('feedback_items', models.JSONField(blank=True, default=list, help_text='User feedback items')),
                ('feature_requests', models.JSONField(blank=True, default=list, help_text='Feature request tracker')),
                ('iteration_roadmap', models.JSONField(blank=True, default=list, help_text='Product iteration roadmap')),
                ('demo_videos', models.JSONField(blank=True, default=list, help_text='Demo video links')),
                ('screenshots', models.JSONField(blank=True, default=list, help_text='Product screenshots')),
                ('presentations', models.JSONField(blank=True, default=list, help_text='Pitch decks and presentations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprinto_data', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sprinto_data', to='pitches.pitch')),
            ],
            options={
                'verbose_name': 'Sprinto Data',
                'verbose_name_plural': 'Sprinto Data',
                'ordering': ['-updated_at'],
            },
        ),
    ]
