# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('call', 'Phone Call'), ('meeting', 'Meeting'), ('pitch', 'Pitch'), ('demo', 'Demo'), ('note', 'Note'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('outcome', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('interaction_date', models.DateTimeField()),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('initial_contact', 'Initial Contact'), ('qualified', 'Qualified'), ('pitch_scheduled', 'Pitch Scheduled'), ('pitch_completed', 'Pitch Completed'), ('negotiation', 'Negotiation'), ('committed', 'Committed'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='initial_contact', max_length=30)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, help_text='Expected deal/investment value', max_digits=12, null=True)),
                ('probability', models.IntegerField(default=0, help_text='Success probability (0-100)')),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline Entry',
                'verbose_name_plural': 'Pipeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('investor', 'Investor'), ('advisor', 'Advisor'), ('mentor', 'Mentor'), ('partner', 'Partner'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('active', 'Active'), ('inactive', 'Inactive')], default='lead', max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('interests', models.JSONField(blank=True, default=list, help_text='Areas of interest')),
                ('investment_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Potential investment amount', max_digits=12, null=True)),
                ('investment_stage_preference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
                'ordering': ['-created_at'],
            },
        ),
    ]
