# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('stakeholders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_stakeholders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='projects.project'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='projects.project'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entries', to='stakeholders.stakeholder'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='stakeholders.stakeholder'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stakeholder',
            index=models.Index(fields=['project', 'type'], name='stakeholder_project_2e0fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholder',
            index=models.Index(fields=['project', 'status'], name='stakeholder_project_9c84a6_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholder',
            index=models.Index(fields=['type', 'status'], name='stakeholder_type_4b4d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['project', 'stage'], name='stakeholder_project_e13516_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['stage', '-created_at'], name='stakeholder_stage_64165d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('project', 'stakeholder')},
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['stakeholder', '-interaction_date'], name='stakeholder_stakeho_4fb4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['user', '-interaction_date'], name='stakeholder_user_id_74a936_idx'),
        ),
    ]
