# Generated by Django 4.2.16 on 2025-11-29 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakeholders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('advisor', 'Advisor'), ('investor', 'Investor'), ('mentor', 'Mentor'), ('early-adopter', 'Early Adopter'), ('beta-tester', 'Beta Tester'), ('supporter', 'Supporter'), ('team-prospect', 'Team Prospect'), ('partner', 'Partner'), ('customer', 'Customer'), ('other', 'Other')], default='advisor', max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('relationship_strength', models.IntegerField(default=5, help_text='1-10 scale')),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_stakeholders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stakeholder',
                'verbose_name_plural': 'User Stakeholders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='stakeholder_user_id_bfcd2d_idx'), models.Index(fields=['user', 'is_favorite'], name='stakeholder_user_id_a117f1_idx'), models.Index(fields=['user', '-created_at'], name='stakeholder_user_id_1da3f0_idx')],
            },
        ),
    ]
