# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='connected_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_scores_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_scores_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user1', '-compatibility_score'], name='matching_ma_user1_i_8d3e48_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user2', '-compatibility_score'], name='matching_ma_user2_i_6946ac_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', '-created_at'], name='matching_ma_status_bb5348_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('user1', models.F('user2')), _negated=True), name='different_users'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['user', 'status'], name='matching_co_user_id_876298_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['connected_user', 'status'], name='matching_co_connect_72c8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['-created_at'], name='matching_co_created_0af7d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('user', 'connected_user')},
        ),
        migrations.AddIndex(
            model_name='compatibilityscore',
            index=models.Index(fields=['user1', '-overall_score'], name='matching_co_user1_i_e43b82_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilityscore',
            index=models.Index(fields=['user2', '-overall_score'], name='matching_co_user2_i_f89ad7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compatibilityscore',
            unique_together={('user1', 'user2')},
        ),
    ]
