# Generated by Django 4.2.16 on 2025-11-24 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('market_size', models.CharField(blank=True, max_length=100)),
                ('target_market', models.TextField()),
                ('competitive_advantage', models.TextField()),
                ('business_model', models.TextField()),
                ('funding_needs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('timeline', models.CharField(blank=True, max_length=200)),
                ('team', models.JSONField(blank=True, default=list)),
                ('skills_needed', models.JSONField(blank=True, default=list)),
                ('industries', models.JSONField(blank=True, default=list)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('validation', 'Validation'), ('prototype', 'Prototype'), ('mvp', 'MVP'), ('growth', 'Growth'), ('scaling', 'Scaling')], default='idea', max_length=20)),
                ('video_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('audio_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('deck_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('is_public', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pitch',
                'verbose_name_plural': 'Pitches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='pitches.pitch')),
            ],
            options={
                'verbose_name': 'Saved Pitch',
                'verbose_name_plural': 'Saved Pitches',
                'ordering': ['-created_at'],
            },
        ),
    ]
