# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpitch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pitches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pitch',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedpitch',
            unique_together={('user', 'pitch')},
        ),
        migrations.AddIndex(
            model_name='pitch',
            index=models.Index(fields=['-created_at'], name='pitches_pit_created_39cea7_idx'),
        ),
        migrations.AddIndex(
            model_name='pitch',
            index=models.Index(fields=['author', '-created_at'], name='pitches_pit_author__938621_idx'),
        ),
        migrations.AddIndex(
            model_name='pitch',
            index=models.Index(fields=['stage', '-created_at'], name='pitches_pit_stage_660155_idx'),
        ),
        migrations.AddIndex(
            model_name='pitch',
            index=models.Index(fields=['is_public', '-created_at'], name='pitches_pit_is_publ_d1f970_idx'),
        ),
    ]
