# Generated by Django 4.2.16 on 2025-11-29 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LikedPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='pitches.pitch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_pitches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liked Pitch',
                'verbose_name_plural': 'Liked Pitches',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'pitch')},
            },
        ),
    ]
