# Generated by Django 4.2.16 on 2025-11-29 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitches', '0003_pitch_likes_count_likedpitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PitchComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pitches.pitchcomment')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pitches.pitch')),
            ],
            options={
                'verbose_name': 'Pitch Comment',
                'verbose_name_plural': 'Pitch Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pitch', '-created_at'], name='pitches_pit_pitch_i_5fd3cd_idx'), models.Index(fields=['author', '-created_at'], name='pitches_pit_author__c48e5a_idx')],
            },
        ),
    ]
