# Generated by Django 4.2.16 on 2025-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0004_pitch_comments_count_pitchcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pitch',
            name='equity_offer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pitch',
            name='funding_stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pitch',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pitch',
            name='looking_for_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pitch',
            name='what_you_bring',
            field=models.TextField(blank=True),
        ),
    ]
