# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('project_url', models.URLField(blank=True)),
                ('technologies', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portfolio_items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('avatar', models.URLField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.CharField(max_length=100)),
                ('previous_startups', models.JSONField(default=list)),
                ('location', models.CharField(max_length=200)),
                ('looking_for', models.JSONField(default=list)),
                ('industries', models.JSONField(default=list)),
                ('archetype', models.CharField(blank=True, choices=[('visionary', 'Visionary'), ('executor', 'Executor'), ('hustler', 'Hustler'), ('technologist', 'Technologist'), ('designer', 'Designer'), ('marketer', 'Marketer')], max_length=50, null=True)),
                ('availability', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('weekends', 'Weekends'), ('flexible', 'Flexible')], default='full-time', max_length=50)),
                ('stage_preference', models.JSONField(default=list)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('profile_views', models.IntegerField(default=0)),
                ('pitch_responses', models.IntegerField(default=0)),
                ('successful_matches', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('accepting_pitches', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(max_length=100)),
                ('author_avatar', models.URLField(blank=True)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='profiles.profile')),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
