# Generated by Django 4.2.16 on 2025-11-25 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_mask',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OnboardingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_statement', models.TextField(blank=True)),
                ('selected_values', models.JSONField(default=list)),
                ('industries', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.CharField(blank=True, max_length=200)),
                ('background', models.TextField(blank=True)),
                ('about_self', models.TextField(blank=True)),
                ('birth_place', models.CharField(blank=True, max_length=200)),
                ('pitch_text', models.TextField(blank=True)),
                ('pitch_format', models.CharField(default='text', max_length=20)),
                ('has_voice_note', models.BooleanField(default=False)),
                ('pitch_deck_file_name', models.CharField(blank=True, max_length=255)),
                ('pitch_deck_file_size', models.CharField(blank=True, max_length=50)),
                ('cofounder_preferences', models.JSONField(default=dict)),
                ('offer_skills_data', models.JSONField(default=dict)),
                ('idea_sprint_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_data',
            },
        ),
    ]
