# Generated by Django 4.2.16 on 2025-11-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_hourlyrate_startupstage_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdata',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='onboardingdata',
            name='work_experience',
            field=models.JSONField(default=list),
        ),
    ]
