# Generated by Django 4.2.16 on 2025-11-24 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Project',
                'verbose_name_plural': 'Client Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('custom', 'Custom')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('delivery_time_days', models.IntegerField(help_text='Delivery time in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('revisions', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['package_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills')),
                ('primary_skills', models.JSONField(blank=True, default=list, help_text='Top 3-5 primary skills')),
                ('industries', models.JSONField(blank=True, default=list, help_text='Industries of expertise')),
                ('years_of_experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-1 years)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3-5 years)'), ('expert', 'Expert (5+ years)')], default='beginner', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('available_for_hire', models.BooleanField(default=False)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_hours_per_week', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Profile',
                'verbose_name_plural': 'Skill Profiles',
            },
        ),
    ]
