# Generated by Django 4.2.16 on 2025-11-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='skills.servicepackage'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='servicepackage',
            index=models.Index(fields=['provider', 'is_active'], name='skills_serv_provide_4a8497_idx'),
        ),
        migrations.AddIndex(
            model_name='clientproject',
            index=models.Index(fields=['client', 'status'], name='skills_clie_client__ed1821_idx'),
        ),
        migrations.AddIndex(
            model_name='clientproject',
            index=models.Index(fields=['service_provider', 'status'], name='skills_clie_service_406ba8_idx'),
        ),
    ]
